name: Generate Auto Changelog
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published
jobs:
  master:
    name: Generate Auto Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Generate Auto Changelog
        uses: elfgzp/action-auto-changelog@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BRANCH: ${{ github.GITHUB_REF }}
